In [27]:
#Ejercicio 3
import numpy as np

valores = np.array(input(f'Ingrese los valores separados por un espacio: ').split(' '), dtype=int)
valores = valores.reshape(5, 1) 

for i in range(5):
    vendidos = np.array(input(f'Ingrese cantidad vendida del producto {i+1} en cada uno en las sucursales, separado por espacios: ').split(' '), dtype=int)
    if (i == 0):
        aux = vendidos
    else:
        aux=np.vstack((aux, vendidos))

print(f'Matriz de cantidades vendidas: \n{aux}')

sucursal2 = 0
for venta in aux[:, 1]:
    sucursal2 += venta
print(f'Cantidad de artículos vendidos en la sucursal 2: {sucursal2}')

sucursal3 = 0
for venta in aux[:, 2]:
    sucursal3 += venta
print(f'Cantidad de artículos vendidos en la sucursal 3: {sucursal3}')

a3s1 = aux[2, 0]
print(f'Cantidad vendida del artículo 3 en la sucursal 1: {a3s1}')


sucursal4 = aux[:, 3]
totals4 = 0
for venta in range(len(sucursal4)): # Itera cada fila
    # Multiplicar el valor de la fila por la cantidad de ventas correspondiente a ese producto
    totals4 += (sucursal4[venta] * valores[venta, 0] )

print(f'Recaudación total de la sucursal 4: {totals4}')

totalempresa = 0
for fila in range(len(aux)):
    # Iteramos cada valor de la fila
    # Y lo multiplicamos por el valor del producto, que está en el mismo índice, que la fila
    total_fila = [articulo * valores[fila] for articulo in aux[fila]]
    totalempresa += sum(total_fila)

print(f'Recaudación total de la empresa: {int(totalempresa)}')



Matriz de cantidades vendidas: 
[[10  9  8  7]
 [ 3  4  5  6]
 [ 1  0  1  1]
 [10 12 12 12]
 [ 5  5 10  6]]
Cantidad de artículos vendidos en la sucursal 2: 30
Cantidad de artículos vendidos en la sucursal 3: 36
Cantidad vendida del artículo 3 en la sucursal 1: 1
Recaudación total de la sucursal 4: 47330
Recaudación total de la empresa: 189990


In [3]:
#Ejercicio 6 

import numpy as np


def matriz_traspuesta(m):
    x,y = m.shape
    m_t = np.empty((y,x), dtype=complex)
    for i in range(x):
        for j in range(y):
            m_t[j,i] = m[i,j]
    return m_t

def real(m,c):
    x,y=m.shape
    real=True
    for i in range(x):
        for j in range(y):
            if m[i,j]!=c[i,j]:
                real=False
                break
    return real


n=int(input('Ingrese dimensión matriz cuadrada: '))
A = np.empty((n,n), dtype=complex)

for i in range(n):
    for j in range(n):
        valor = complex( input(f'Ingrese valor {i,j}: ') )
        A[i,j] = valor
       
    
C=A.conjugate()


if real(A,C):
    traspuesta=matriz_traspuesta(A)
    print(traspuesta)
    seguir=True
    simetrica=True
    for i in range(n):
        for j in range(n):
            if traspuesta[i,j]!=A[i,j]:
                simetrica=False
                break
    if simetrica:
        print('Sí, es simétrica')
    else:
        print('No es simétrica')

else:
    traspuesta=matriz_traspuesta(C)
    print(traspuesta)
    seguir=True
    simetrica=True
    for i in range(n):
        for j in range(n):
            if traspuesta[i,j]!=A[i,j]:
                simetrica=False
                break
    if simetrica:
        print('Sí, es hermitiana')
    else:
        print('No es hermitiana')

[[5.-0.j 3.+7.j]
 [3.-7.j 2.-0.j]]
Sí, es hermitiana
